# improve colors
set -g terminal-overrides 'rxvt-unicode*:sitm@,ritm@'
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux"

set-option -g focus-events on
set -g detach-on-destroy off
set -g escape-time 0         # zero-out escape time delay
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
set -g status-interval 3     # update the status bar every 3 seconds
set -g status-position top   # macOS / darwin style


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# quiet
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Remove escape delay
set -s escape-time 0

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# mouse mode
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

set -g prefix2 C-f

# tmux prefix
unbind C-b
set -g prefix C-f

#Enable screen-like C-f C-f moving to last window
bind-key C-f last-window

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# use vim key bindings
set-window-option -g mode-keys vi
unbind =
bind = select-layout tiled

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set-window-option -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# Go to beginning of line
bind a send-prefix

# increase scrollback lines
set -g history-limit 10000

# prefix -> back-one-character
bind-key C-b send-prefix
# prefix-2 -> forward-incremental-history-search
bind-key C-s send-prefix -2

# don't suspend-client
unbind-key C-z

bind -r D neww -c "#{pane_current_path}" "nvim ~/vimwiki/diary/$(date +%Y-%m-%d).wiki"
bind-key -r o run-shell "tmux neww ~/dotfiles/bin/tmux-session"
bind-key -r W run-shell "~/dotfiles/bin/tmux-session ~/vimwiki"
bind-key -r m run-shell "~/dotfiles/bin/tmux-session ~/Developer/src/github.com/moneykit/moneykit-api"
bind-key -r a run-shell "~/dotfiles/bin/tmux-session ~/Developer/src/github.com/moneykit/money-app-api"

# Status Bar
set -g status on
set -g status-left-length 60
set -g status-interval 15
set -g status-justify centre
set -g status-keys vi
set -g status-style fg=colour136,bg="#002b36"

set -g status-left " #[fg=green]#S#[default]"
# set -g status-right "#{pomodoro_status}#[default]%l:%M%p #{battery_color_charge_fg}#{battery_icon_charge} "
set -g status-right "#{pomodoro_status}#[default]%l:%M%p "

# Colors
set -g status-bg colour235
set -g status-fg white

# Open lazygit in a popup
bind-key g display-popup -w "80%" -h "80%" -d "#{pane_current_path}" -E "lazygit"

# Pomo settings
set -g @pomodoro_auto_restart true
set -g @pomodoro_start 'p'
set -g @pomodoro_cancel 'p'
set -g @pomodoro_on "#[fg=yellow]"
set -g @pomodoro_complete "#[fg=red]"
set -g @pomodoro_notifications 'off'
set -g @pomodoro_sound 'Blow.aiff'

# Local config
if-shell "[ -f ~/.tmux.conf.local ]" 'source ~/.tmux.conf.local'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

run '~/.tmux/plugins/tpm/tpm'
