"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$localip\
$directory\
[$git_branch$git_commit$git_state$git_metrics$git_status](green bold)\
$sudo\
$fill\
$cmd_duration\
$jobs\
$time\
$status\
$battery\
$line_break\
$character"""

[package]
disabled = true

[fill]
symbol = " "

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"

[git_branch]
format = "[$branch]($style) "
style = "green"

[localip]
ssh_only = true
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
